name: Deploy

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: |
          cd vue-project
          pnpm install
          cd ..

      - name: Build
        run: |
          cd vue-project
          pnpm build
          cd ..

      - name: Add dist to git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add vue-project/dist
          git commit -m "Deploy"

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: deploy
      
      - name: Sync
        run: curl https://eis.zzzing.cn/update?token=${{ secrets.SYNC_TOKEN }}
