name: Deploy

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: |
          cd vue-project
          pnpm install
          cd ..

      - name: Build
        run: |
          cd vue-project
          pnpm build
          cd ..

      - name: Clear deploy branch
        run: |
          git branch -D deploy
          git checkout -b deploy
      
      - name: Copy files
        run: |
          git checkout main
          cp -r flask-project deploy/
          cp -r vue-project/dist deploy/

      - name: Commit changes
        run: |
          git add .
          git commit -m "Deploy"
          git push -f origin deploy
    
