name: Deploy

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: |
          cd vue-project
          pnpm install
          cd ..

      - name: Build
        run: |
          cd vue-project
          pnpm build
          cd ..

      - name: Clear deploy branch
        run: |
          git branch -D deploy || true
          git checkout -B deploy
      
      - name: Copy files
        run: |
          git checkout main
          cp -r flask-project deploy/
          cp -r vue-project/dist deploy/

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Commit changes
        run: |
          git add .
          git commit -m "Deploy to deploy branch" -a || true  # 防止没有更改时出错

      - name: Push changes
        run: |
          git push -f origin deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}